# Generated by Django 3.1 on 2020-08-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo do Projeto')),
                ('ano', models.IntegerField(verbose_name='Ano do Projeto')),
                ('aprovado', models.BooleanField(verbose_name='Aprovado SIM ou NAO')),
            ],
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matricula')),
                ('nome', models.CharField(max_length=90, verbose_name='Nome do Aluno')),
                ('Participa', models.ManyToManyField(to='core.Participa', verbose_name='Participacoes')),
            ],
        ),
    ]
