# Generated by Django 3.1 on 2020-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200809_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado SIM ou NAO'),
        ),
    ]
